### PR TITLE
verifying resource name length

### PR DESCRIPTION
**Pull request by dcaro**
Fixing issue #8

---
This change is [Reviewable](https://reviewable.io/reviews/yaronyg/sleeveforarm/21)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/cli.ts, line 25 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-Ktsu3ZsOqP60LXr1SA4:-Ktsu3ZtJB52js2Th-FI:bm7jozs) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/cli.ts#L25)):*
> ```XML
>       if (!(await CommonUtilities.validatelength(Path.basename(process.cwd()),
>                                              ProjectNameLength))) {
>       throw new Error(`Project name should be less than ${ProjectNameLength}`);
> ```

The indenting doesn't look right here, I wonder if it's an artifact of the review tool?

Also I think the error should be "Project name should be less than ${ProjectNameLength} characters long."

Also shouldn't we check that the name is only alphanumeric?

---

*[src/common-utilities.ts, line 239 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuHFV-L4BUXzsjbIR:-KtsuHFV-L4BUXzsjbIS:b743mqn) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/common-utilities.ts#L239)):*
> ```XML
> 
> export function validatelength(resourcename: string, length: number) {
>     if (resourcename.length < length) {
> ```

Would "return resourcename.length < length;" be more concise?

---

*[src/keyvaultInfrastructure.ts, line 7 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuPrMyQfu2k6uMVJb:-KtsuPrMyQfu2k6uMVJc:b9j2v2a) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/keyvaultInfrastructure.ts#L7)):*
> ```XML
> import * as Resource from "./resource";
> 
> const KVNameLenght: number = 24;
> ```

/Lenght/Length/

---

*[src/resource.ts, line 23 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuYEIjrlkaTBWFySn:-KtsuYEIjrlkaTBWFySo:b-5dhzpt) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L23)):*
> ```XML
>     protected static async internalSetup(fileName: string,
>                                          targetDirectoryPath: string,
>                                          length: number)
> ```

A more descriptive name would, I think, be useful. Like "maximumNameLength"

---

*[src/resource.ts, line 27 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuwZ7KmGeT-snSgVu:-KtsuwZ7KmGeT-snSgVv:b-6d4w9l) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L27)):*
> ```XML
>         if (!(await CommonUtilities.validatelength(
>                             (Path.basename(targetDirectoryPath)), length))) {
>             await fs.removeAsync(targetDirectoryPath);
> ```

Having to call removeAsync makes me sad. Why don't we take the code at the start of setup() in cliUtilities (the part that creates the directory) and move it into internalSetup? It feels much cleaner.

---

*[src/resource.ts, line 30 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvF1usZsRPG3pccsV:-KtsvF1usZsRPG3pccsW:b57x0md) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L30)):*
> ```XML
>             throw new Error(
>                 `The name of the resource ${Path.basename(targetDirectoryPath)}\
>  is longer than expected ${length}` );
> ```

I would suggest an error like "The name of the resource ${} is longer than the maximum number of character ${length}"

Also shouldn't we check that the name is alpha numeric?

---

*[src/webapp-node-azureInfrastructure.ts, line 13 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvSG5fr1_cDvbEglB:-KtsvSG5fr1_cDvbEglC:b9j2v2a) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/webapp-node-azureInfrastructure.ts#L13)):*
> ```XML
> import WebappNodeAzure from "./webapp-node-azure";
> 
> const WebAppLenght: number = 25;
> ```

/Lenght/Length/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by dcaro** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/cli.ts, line 25 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-Ktsu3ZsOqP60LXr1SA4:-KtsxQLu7K_9dAG04s0l:b-vo5fj3) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/cli.ts#L25)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

The indenting doesn't look right here, I wonder if it's an artifact of the review tool?

Also I think the error should be "Project name should be less than ${ProjectNameLength} characters long."

Also shouldn't we check that the name is only alphanumeric?
</blockquote></details>

Added with a simple regex.

---

*[src/common-utilities.ts, line 239 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuHFV-L4BUXzsjbIR:-KtsxJIeQxDm-74aP2OF:b-o47auz) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/common-utilities.ts#L239)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Would "return resourcename.length < length;" be more concise?
</blockquote></details>

it is more elegant :)  did so. 

---

*[src/keyvaultInfrastructure.ts, line 7 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuPrMyQfu2k6uMVJb:-Ktsy30QaIDnrzxvHCTE:b4ax0f1) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/keyvaultInfrastructure.ts#L7)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

/Lenght/Length/
</blockquote></details>

typo fixed

---

*[src/resource.ts, line 23 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuYEIjrlkaTBWFySn:-Ktsx7IfRs6TmW46HWxp:b-i5t8yx) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L23)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

A more descriptive name would, I think, be useful. Like "maximumNameLength"
</blockquote></details>

Agree, change done.

---

*[src/resource.ts, line 27 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuwZ7KmGeT-snSgVu:-KtswUiuVwUTytvi2Ozc:b3pxng8) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L27)):*
> It was my initial plan and faced some issues importing the data file. I will try to look at that again but I'm not sure that I can do that before tomorrow.

---

*[src/resource.ts, line 30 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvF1usZsRPG3pccsV:-Ktswz3amHSbUOWZNZ3z:b81p2gl) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I would suggest an error like "The name of the resource ${} is longer than the maximum number of character ${length}"

Also shouldn't we check that the name is alpha numeric?
</blockquote></details>

I forgot the alphanumeric check, just did it in a validateResource function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by dcaro** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/webapp-node-azureInfrastructure.ts, line 13 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvSG5fr1_cDvbEglB:-Kttg4sKDTSoNropsIz0:b-896fix) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/webapp-node-azureInfrastructure.ts#L13)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

/Lenght/Length/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by yaronyg** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/resource.ts, line 27 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsuwZ7KmGeT-snSgVu:-Ktvro-aITCKf5qXejoa:b-lm69zh) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L27)):*
<details><summary><i>Previously, dcaro (Damien Caro) wrote…</i></summary><blockquote>

> It was my initial plan and faced some issues importing the data file. I will try to look at that again but I'm not sure that I can do that before tomorrow.
</blockquote></details>

That's fine. I'm working in my own branch for now anyway.

---

*[src/resource.ts, line 30 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvF1usZsRPG3pccsV:-Ktvrurhzd4gIVi--VZV:b-4qnps1) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/resource.ts#L30)):*
<details><summary><i>Previously, dcaro (Damien Caro) wrote…</i></summary><blockquote>

I forgot the alphanumeric check, just did it in a validateResource function
</blockquote></details>

Please also update the error message to make it clear we are talking about the number of characters in the name.

---

*[src/webapp-node-azureInfrastructure.ts, line 13 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvSG5fr1_cDvbEglB:-Ktvs-WJce3a9jAd3cZW:bpw1lhv) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/webapp-node-azureInfrastructure.ts#L13)):*
<details><summary><i>Previously, dcaro (Damien Caro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change here. Are you sure you pushed the PR with that change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by dcaro** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/webapp-node-azureInfrastructure.ts, line 13 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvSG5fr1_cDvbEglB:-KtvunswU2mLepsgw1tZ:b-7eetyb) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/webapp-node-azureInfrastructure.ts#L13)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I don't see the change here. Are you sure you pushed the PR with that change?
</blockquote></details>

kof kof ... with Ctrl+S would help :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/webapp-node-azureInfrastructure.ts, line 13 at r1](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtsvSG5fr1_cDvbEglB:-KtvyoPuKeQLhRhZCBU8:b-9c1sub) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/51361a4895758b27c7cfb989f1831605819f7a6e/src/webapp-node-azureInfrastructure.ts#L13)):*
<details><summary><i>Previously, dcaro (Damien Caro) wrote…</i></summary><blockquote>

kof kof ... with Ctrl+S would help :)
</blockquote></details>

I use https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save. It makes life much easier. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Comment by yaronyg** [comment]
Reviewed 1 of 4 files at r2, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/cliUtilities.ts, line 48 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtxRO3M5qtTjtGlFWLj:-KtxRO3M5qtTjtGlFWLk:b-3k8k4l) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/cliUtilities.ts#L48)):*
> ```XML
> export async function setup(rootPath: string, serviceName: string,
>                             serviceType: string) {
>     // Moving this code to internal setup 
> ```

Please delete this and the code below before submitting

---

*[src/common-utilities.ts, line 239 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtxS9dsFEnUxpw5tWH7:-KtxS9dsFEnUxpw5tWH8:bnf983k) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/common-utilities.ts#L239)):*
> ```XML
> 
> export function validateResource(resourcename: string, length: number) {
>     return ((resourcename.length < length) &&
> ```

Something doesn't feel quite right here. When we call validateResource, for example, KeyVault. The length for KeyVault is 24 characters and what we pass in is the key vault's directory name. Which means that so long as the directory name is 24 characters then this function will pass. But that isn't right! The reason is that we reserve 10 characters for the project name and another 4 characters for location and deployment type. So that means we should fail anything under 24 - 10 - 4 characters. Shouldn't we?

BTW there is also a tricky scenario here. In the specific case of checking a resource group name (during Init right now, but in the future we will let users create custom resource groups) we have to make sure we don't subtract the 10 characters for the resource group name (since, well, it's the resource group's name already!), just the 4 characters for location and deployment type. So we should probably have a switch that says if we are a resource group.

---

*[src/common-utilities.ts, line 240 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtxSr0h7p6_6LYkjr20:-KtxSr0ioZiTsygMG9MV:b-oqp29z) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/common-utilities.ts#L240)):*
> ```XML
> export function validateResource(resourcename: string, length: number) {
>     return ((resourcename.length < length) &&
>             (RegExp("^[a-zA-Z][a-zA-Z0-9]+$").test(resourcename)));
> ```

When we introduced this function and the associated errors all it did was check length. But now it checks two different things, length and if the characters in the name are acceptable. But how is someone calling the function supposed to know what caused the error? And without that information how do we return a good error message?

In these situations there are two choices. One is to return void and throw an error that explains what went wrong (ideally an error that is human readable). The other slightly nastier choice is to return a string. If everything is fine the string is empty (we don't want to use null as that messes up typing). If the string isn't null then we have an error and the string will explain the error. I think we need to use one of those two approaches.

---

*[src/resource.ts, line 27 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtxU2udfu-k79PYAREn:-KtxU2udfu-k79PYAREo:b-kgi47u) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/resource.ts#L27)):*
> ```XML
>         const serviceName = Path.basename(targetDirectoryPath);
>         if (!(await CommonUtilities.validateResource(
>                     (serviceName), maximumNameLength))) {
> ```

Why is serviceName inside of a parenthesis?

---

*[src/resource.ts, line 31 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-KtxUBupR5L99oaPmC1P:-KtxUBupR5L99oaPmC1Q:b3af77e) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/resource.ts#L31)):*
> ```XML
>                 `The name of the resource ${Path.basename(targetDirectoryPath)}\
>  should be less than ${maximumNameLength} characters,\
>  contains only alphanumeric characters and start with a letter\n` );
> ```

I think it should say "characters and contains" although per my previous suggestion it's nicer if we just tell the user what went wrong (e.g. was it a length or character issue?)

---

*[src/resource.ts, line 34 at r4](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21#-Ku0QX7On8mns_sF-WOQ:-Ku0QX7On8mns_sF-WOR:bfp7kte) ([raw file](https://github.com/yaronyg/sleeveforarm/blob/82d9caa9d7ba9651ec7f33a6fdd2319b22c974ee/src/resource.ts#L34)):*
> ```XML
>         }
> 
>         if (fs.existsSync(targetDirectoryPath)) {
> ```

It's not a huge deal but why have a sync command here when we use async everywhere else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/yaronyg/sleeveforarm/21)*

**Pull request merged**
